CREATE DATABASE StoreDB
GO
USE StoreDB

CREATE TABLE Store
(
	StoreID INT PRIMARY KEY,
	StoreName VARCHAR(50) NOT NULL
)

CREATE TABLE Employee
(
	EmployeeID INT PRIMARY KEY,
	EName VARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	StoreID INT FOREIGN KEY REFERENCES Store(StoreID)
)

CREATE TABLE Client
(
	CNP VARCHAR(50) PRIMARY KEY,
	CName VARCHAR(50) NOT NULL,
)

CREATE TABLE Car
(
	CarID INT PRIMARY KEY,
	CarModel VARCHAR(50) NOT NULL,
	Price INT NOT NULL,
	Color VARCHAR(50) NOT NULL,
	FabricationDate DATE NOT NULL,
	EngineCapacity VARCHAR(50) NOT NULL,
	HorsePower VARCHAR(50) NOT NULL,
	StoreID INT FOREIGN KEY REFERENCES Store(StoreID)
)

CREATE TABLE Floor
(
	FloorID INT PRIMARY KEY,
	Capacity INT NOT NULL
)

CREATE TABLE Office
(
	OfficeID INT PRIMARY KEY,
	StoreID INT FOREIGN KEY REFERENCES Store(StoreID),
	FloorID INT FOREIGN KEY REFERENCES Floor(FloorID)
)

CREATE TABLE Promotion
(
	PromoID INT PRIMARY KEY,
	Procent INT DEFAULT 0,
	AvailabilityDate DATE DEFAULT 'TBD'
)

CREATE TABLE Contract
(
	CNP VARCHAR(50) FOREIGN KEY REFERENCES Client(CNP),
	CarID INT FOREIGN KEY REFERENCES Car(CarID),
	CONSTRAINT PK_ClientCar PRIMARY KEY (CNP, CarID)
)

CREATE TABLE PromoCar
(
	CarID INT FOREIGN KEY REFERENCES Car(CarID),
	PromoID INT FOREIGN KEY REFERENCES Promotion(PromoID),
	CONSTRAINT PK_PromoCar PRIMARY KEY (PromoID, CarID)
)

CREATE TABLE EmployeeClient
(
	CNP VARCHAR(50) FOREIGN KEY REFERENCES Client(CNP),
	EmployeeID INT FOREIGN KEY REFERENCES Employee(EmployeeID),
	CONSTRAINT PK_EmployeeClient PRIMARY KEY (CNP, EmployeeID)
)
